# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0002_auto_20171121_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
