# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0004_auto_20171121_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='video',
            name='searched',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='video',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
