# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0005_auto_20171121_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(default='/static/img/default.png', upload_to='img/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='videos/%Y/%m/%d'),
        ),
    ]
