# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 05:25
from __future__ import unicode_literals

from django.db import migrations
import videothumbs.fields


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0007_auto_20171122_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=videothumbs.fields.VideoThumbnailField(default='img/default.png', upload_to='img/%Y/%m/'),
        ),
    ]
